import { Multiplayer } from './multiplayer.js';
import { RaceGame } from './race.js';

const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const app=$('#app'); const netBadge=$('#networkBadge');
let cars=[],maps=[]; let screen='home'; let mode='solo'; let selectedCar=null,selectedMap=null; let race=null; let lobbyState=null;

const mp=new Multiplayer(state=>{lobbyState=state;if(screen==='lobby')renderLobbyState();});

async function loadData(){[cars,maps]=await Promise.all([fetch('./data/cars.json').then(r=>r.json()),fetch('./data/maps.json').then(r=>r.json())]);selectedCar=cars[0];selectedMap=maps[0];renderHome();}
function clone(id){return document.getElementById(id).content.cloneNode(true)}
function toast(msg){const d=document.createElement('div');d.className='toast';d.textContent=msg;document.body.appendChild(d);setTimeout(()=>d.remove(),2400)}
function setNetwork(ok){netBadge.textContent=ok?'ONLINE':'OFFLINE';netBadge.classList.toggle('muted',!ok)}

function renderHome(){screen='home';app.replaceChildren(clone('homeTemplate'));$('#homeCars').textContent=cars.length;$('#homeMaps').textContent=maps.length;bindCommon();}
function bindCommon(){ $$('[data-action="home"]').forEach(b=>b.onclick=()=>{if(race){race.stop();race=null}renderHome()}); $('[data-action="solo"]')?.addEventListener('click',()=>{mode='solo';renderSelect('car')}); $('[data-action="multiplayer"]')?.addEventListener('click',renderMultiplayer); }

function renderSelect(type){screen=type==='car'?'select-car':'select-map';app.replaceChildren(clone('selectTemplate'));bindCommon();const grid=$('#cardGrid'),continueBtn=$('#selectContinue'),stepper=$('.stepper');if(type==='map'){ $('#selectEyebrow').textContent='TRACK SELECT';$('#selectTitle').textContent='Pilih Map';stepper.innerHTML='<span>1</span><i></i><span class="active">2</span>';} const data=type==='car'?cars:maps;data.forEach(item=>grid.appendChild(type==='car'?carCard(item):mapCard(item)));const current=type==='car'?selectedCar:selectedMap;markSelected(current?.id);updateSummary(type,current);continueBtn.disabled=!current;continueBtn.onclick=()=>type==='car'?renderSelect('map'):startRace({map:selectedMap,car:selectedCar,laps:3});$('[data-action="back"]').onclick=()=>type==='car'?renderHome():renderSelect('car');function markSelected(id){$$('.select-card').forEach(c=>c.classList.toggle('selected',c.dataset.id===id))}function choose(item){if(type==='car')selectedCar=item;else selectedMap=item;markSelected(item.id);updateSummary(type,item);continueBtn.disabled=false}$$('.select-card').forEach(card=>card.onclick=()=>choose(data.find(x=>x.id===card.dataset.id)));}
function updateSummary(type,item){$('#selectionSummary').innerHTML=item?`Dipilih: <b>${type==='car'?item.name:item.city+' — '+item.name}</b>`:'Belum ada pilihan';}
function carCard(c){const d=document.createElement('article');d.className='select-card';d.dataset.id=c.id;d.innerHTML=`<span class="tag">${c.class}</span><h3>${c.name}</h3><p>${c.id==='civic-type-r'?'Track weapon':'Honda performance setup'}</p><div class="car-art"><div class="car-shape" style="--car-color:${c.color}"></div></div><div class="stats">${[['SPEED',c.speed],['ACCEL',c.accel],['HANDLING',c.handling]].map(([n,v])=>`<div class="stat"><span>${n}</span><div class="stat-track"><i style="width:${v}%"></i></div><b>${v}</b></div>`).join('')}</div>`;return d}
function mapCard(m){const d=document.createElement('article');d.className='select-card';d.dataset.id=m.id;d.innerHTML=`<span class="tag">${m.difficulty}</span><h3>${m.name}</h3><p>${m.city}</p><div class="map-art" style="--sky1:${m.sky1};--sky2:${m.sky2};--landmark:${m.landmark};--shape:${m.shape}"></div><div class="stat"><span>STYLE</span><div class="stat-track"><i style="width:${m.difficulty==='EASY'?45:m.difficulty==='MEDIUM'?70:95}%"></i></div><b>${m.difficulty[0]}</b></div>`;return d}

function renderMultiplayer(){screen='multiplayer';app.replaceChildren(clone('multiplayerTemplate'));bindCommon();const cfg=mp.getConfig();$('#supabaseUrl').value=cfg.url;$('#supabaseKey').value=cfg.key;$('#playerName').value=localStorage.getItem('hsr_name')||'';updateConfigStatus();$('#saveSupabaseBtn').onclick=()=>{mp.saveConfig($('#supabaseUrl').value,$('#supabaseKey').value);updateConfigStatus();toast('Konfigurasi Supabase tersimpan')};$('#createRoomBtn').onclick=async()=>{const name=playerName();if(!name)return toast('Isi nama pemain dulu');try{setBusy(true);await mp.createRoom(name,selectedCar.id);setNetwork(true);renderLobby()}catch(e){toast(e.message)}finally{setBusy(false)}};$('#joinRoomBtn').onclick=async()=>{const name=playerName(),code=$('#roomCodeInput').value.trim().toUpperCase();if(!name)return toast('Isi nama pemain dulu');if(code.length!==6)return toast('Kode room harus 6 karakter');try{setBusy(true);await mp.joinRoom(code,name,selectedCar.id);setNetwork(true);renderLobby()}catch(e){toast(e.message)}finally{setBusy(false)}};function playerName(){const n=$('#playerName').value.trim();if(n)localStorage.setItem('hsr_name',n);return n}function setBusy(v){$('#createRoomBtn').disabled=v;$('#joinRoomBtn').disabled=v}function updateConfigStatus(){const {url,key}=mp.getConfig(),el=$('#supabaseStatus');el.className='connection-status '+(url&&key?'ok':'bad');el.textContent=url&&key?'✓ Konfigurasi tersimpan — siap connect':'Belum dikonfigurasi';}}

function renderLobby(){screen='lobby';app.replaceChildren(clone('lobbyTemplate'));cars.forEach(c=>$('#lobbyCar').insertAdjacentHTML('beforeend',`<option value="${c.id}">${c.name}</option>`));maps.forEach(m=>$('#lobbyMap').insertAdjacentHTML('beforeend',`<option value="${m.id}">${m.city} — ${m.name}</option>`));$('#lobbyCar').value=selectedCar.id;$('#lobbyMap').value=mp.settings.mapId;$('#lobbyLaps').value=String(mp.settings.laps);$('#leaveRoomBtn').onclick=async()=>{await mp.leave();setNetwork(false);renderMultiplayer()};$('#copyRoomBtn').onclick=async()=>{await navigator.clipboard?.writeText(mp.roomCode);toast('Kode room disalin')};$('#lobbyCar').onchange=async e=>{selectedCar=cars.find(c=>c.id===e.target.value);await mp.updateSelf({carId:selectedCar.id,ready:false})};$('#readyBtn').onclick=async()=>{const me=mp.players.get(mp.playerId);await mp.updateSelf({ready:!me?.ready,carId:$('#lobbyCar').value})};$('#lobbyMap').onchange=e=>mp.setSettings({mapId:e.target.value});$('#lobbyLaps').onchange=e=>mp.setSettings({laps:Number(e.target.value)});$('#startRaceBtn').onclick=async()=>{const players=[...mp.players.values()];if(!mp.isHost)return; if(players.length<2)return toast('Butuh minimal 2 pemain'); if(players.some(p=>!p.ready&&!p.host))return toast('Masih ada pemain yang belum READY');const data={mapId:$('#lobbyMap').value,laps:Number($('#lobbyLaps').value),startAt:Date.now()+1800};await mp.broadcast('START_RACE',data);startMultiplayerRace(data)}; mp.onMessage(msg=>{if(screen==='lobby'&&msg.type==='START_RACE')startMultiplayerRace(msg.data)});renderLobbyState();}
function renderLobbyState(){if(screen!=='lobby')return;const s=lobbyState||mp.snapshot();$('#roomCodeDisplay').textContent=s.roomCode||'------';$('#hostBadge').textContent=s.isHost?'HOST':'PLAYER';$('#playerCount').textContent=`${s.players.length} / 6`;$('#lobbyMap').disabled=!s.isHost;$('#lobbyLaps').disabled=!s.isHost;$('#startRaceBtn').style.display=s.isHost?'block':'none';$('#lobbyMap').value=s.settings.mapId;$('#lobbyLaps').value=String(s.settings.laps);const list=$('#playerList');list.innerHTML='';s.players.sort((a,b)=>(b.host?1:0)-(a.host?1:0)||a.joinedAt-b.joinedAt).forEach(p=>{const c=cars.find(x=>x.id===p.carId)||cars[0];const el=document.createElement('div');el.className='player-item';el.innerHTML=`<div class="avatar">${p.host?'👑':p.name.slice(0,1).toUpperCase()}</div><div><b>${escapeHtml(p.name)} ${p.id===mp.playerId?'(Kamu)':''}</b><small>${c.name}</small></div><span class="ready-status ${p.ready?'ready':''}">${p.host?'HOST':p.ready?'READY':'WAIT'}</span>`;list.appendChild(el)});const me=mp.players.get(mp.playerId);$('#readyBtn').textContent=me?.ready?'CANCEL READY':'READY';$('#readyBtn').className=(me?.ready?'ghost':'secondary')+' full';}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function startMultiplayerRace(data){selectedMap=maps.find(m=>m.id===data.mapId)||maps[0];const me=mp.players.get(mp.playerId);selectedCar=cars.find(c=>c.id===(me?.carId||selectedCar.id))||cars[0];startRace({map:selectedMap,car:selectedCar,laps:data.laps,multiplayer:true});}

function startRace({map,car,laps,multiplayer=false}){screen='race';app.replaceChildren(clone('raceTemplate'));$('#hudMap').textContent=`${map.city.toUpperCase()} — ${map.name.toUpperCase()}`;$('#hudLap').textContent=`1/${laps}`;race=new RaceGame({canvas:$('#raceCanvas'),car,map,laps,multiplayer:multiplayer?mp:null,playerId:mp.playerId,onFinish:result=>showResult(result,multiplayer),onExit:()=>multiplayer?renderLobby():renderHome()});race.bindTouch($('#leftBtn'),$('#rightBtn'),$('#boostBtn'));const cd=$('#countdown');let iv=setInterval(()=>{if(!race||screen!=='race'){clearInterval(iv);return}cd.textContent=race.started?'GO!':Math.max(1,race.countdown);if(race.started)setTimeout(()=>cd.classList.add('hidden'),700);$('#hudSpeed').textContent=Math.round(race.speed);$('#hudLap').textContent=`${race.lap}/${laps}`;$('#hudPosition').textContent=`${race.position}/${multiplayer?Math.max(1,mp.players.size):6}`;$('#boostFill').style.width=race.boost+'%';},80);$('#pauseBtn').onclick=()=>showPause(multiplayer);race.start();}
function showPause(multiplayer){if(!race)return;const over=$('#raceOverlay');over.classList.remove('hidden');const was=race.running;race.running=false;over.innerHTML=`<div class="result-card"><div class="eyebrow">PAUSED</div><h2>Race Paused</h2><div class="result-actions"><button id="resume" class="primary">LANJUT</button><button id="quit" class="ghost">KELUAR</button></div></div>`;$('#resume').onclick=()=>{over.classList.add('hidden');race.running=true;race.last=performance.now();requestAnimationFrame(race.loop)};$('#quit').onclick=()=>{race.stop();race=null;multiplayer?renderLobby():renderHome()};}
function showResult(result,multiplayer){const over=$('#raceOverlay');over.classList.remove('hidden');over.innerHTML=`<div class="result-card"><div class="eyebrow">RACE COMPLETE</div><div class="place">#${result.position}</div><h2>FINISH!</h2><p>${selectedMap.city} — ${selectedMap.name}</p><div class="result-actions"><button id="again" class="primary">RACE AGAIN</button><button id="menu" class="ghost">${multiplayer?'LOBBY':'HOME'}</button></div></div>`;$('#again').onclick=()=>startRace({map:selectedMap,car:selectedCar,laps:race?.totalLaps||3,multiplayer});$('#menu').onclick=()=>multiplayer?renderLobby():renderHome();}

loadData().catch(err=>{app.innerHTML=`<div style="padding:40px">Gagal memuat game: ${err.message}</div>`});
